### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by Ashlon1** [trickerer/Trinity-Bots#661] opened 2023-10-17 15:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour
Trinitycore and NPC Bots won`t compile.

I use to day 17-10-2023 the latest TrinitiCore 3.3.5 and latest NPC Bot.

If I compile TrinitiCore without NPC Bot it compile and I can play the game.

When I apply the patch -p1 < NPCBots.patch on TrinityCore it patch with no error`s.

Cmake build Trinitycore 3.3.5 merged with NPC Bot without problem.

When I compile it with Visual Studio 2022 it failed.

========== Build: 22 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========

### Expected behaviour

The latest TrinityCore and NPC Bot should have no problem compiling it.

### Steps to reproduce the problem

1. Add the latest patch -p1 < NPCBots.patch to the latest Trinitycore 3.3.5
2. Let Cmake configure it and and generate the .sln file.
3. Compile it with Visual Studio 2022.
4. Then I get this error in VS 2022:  22 succeeded, 2 failed, 1 skipped
5.
![Schermafbeelding_2023-10-16_230914](https://github.com/trickerer/Trinity-Bots/assets/16739708/0bb63801-685e-4b7c-984b-026e9c06b683)

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

I can`t because it won`t compile

### Operating system

Win 11

**Comment by trickerer** [comment] 2023-10-18 00:43
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/654

**Closed by trickerer** 2023-10-18 00:43 UTC
Labels: bug
