### ISSUE TITLE
Bot rebind issue

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#324] opened 2023-01-16 09:02 UTC
Thank you for solving the first two crash problems. My server never crashed again
And I am sorry, but i dont kown why. My server still shows: Must target your unbound npcbot whether argument chose target or name.
Is it possible to add `npcbot command rebind all` to rebind all the unbound bots.

**Comment by EvilCalf** [comment] 2023-01-16 09:06
My issue is different from #315. My bot is automatic out of control or disappear. When use `npcb info`, these bots showed as unbound bot.

**Comment by trickerer** [comment] 2023-01-16 09:33
> Is it possible to add npcbot command rebind all to rebind all the unbound bots.
> My issue is different from https://github.com/trickerer/Trinity-Bots/issues/315. My bot is automatic out of control or disappear. When use npcb info, these bots showed as unbound bot.

New command won't help here. If you didn't `.npcb command unbind` a bot you cannot re-bind it. The fact that it is show as unbound in the info only means the bot is inactive (not currently traveling along with the owner). Normally those two things are the same, but if bot doesn't join at login this is a different problem

Bots do not automatically join GMs in GM mode or if bots are disabled in config, that's it.

Describe your problem better: what exactly you're doing and what you get. This exactly why issue template exists

**Comment by EvilCalf** [comment] 2023-01-17 12:03
After some characters go online, the robot will have two situations.
One shows inactivate bot, and the other shows unbound bot.
![image](https://user-images.githubusercontent.com/35754619/212893950-0bdce1ba-4689-45ef-a2ff-39cc155ddbfb.png)
First situation, bots run back and forth as follows.
![image](https://user-images.githubusercontent.com/35754619/212894071-75dd7cda-e7a2-4a74-b160-c0fd5690dbaa.png)
And the other the bots disappear.

**Comment by trickerer** [comment] 2023-01-18 03:22
Woah, that's something.
Looks like bots can't reach thir home location. As for disappearing - not sure.

First, try to check home locations of those runners. Get their id using `.npc info`. Then:
`.gm on`
`.gm fly on`
`.go cre id <ID>`

See if the location is reachable at all. Try to do the same for disappearing bots, you'll have to get their ids some other way.

Check the console for errors while you do this - invalid coords and whatnot

**Comment by EvilCalf** [comment] 2023-01-18 04:13
This is data in characters_npcbot:
![image](https://user-images.githubusercontent.com/35754619/213081778-098ea5c7-7751-4b0b-9efd-c46e2c55d3aa.png)
This is data in creature:
![image](https://user-images.githubusercontent.com/35754619/213081900-f7de7751-63e7-4227-8dfc-fe0327698548.png)
And in game when I use `.go cre id <ID>`.The game shows not found. I am sorry the text is in zhCN.
![image](https://user-images.githubusercontent.com/35754619/213082042-a8820ee0-1c56-47b2-a1f2-311e58104d45.png)

**Comment by trickerer** [comment] 2023-01-18 08:12
Managed to reproduce with bot spawned in Northshire being removed on logout in Stormwind. Seems like the distance they try to walk is too long (1000 yds) and causes all sorts of problems. Reducing the distance fixes it.

Try to patch this single line in manually and see how it works
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/96924f3c7babc9d92ed932b4771d7c5989678683

**Comment by EvilCalf** [comment] 2023-01-23 12:12
There are still problems that some bots show inactivate after being online.
And it seems always one is activate and the other is inactivate.

**Comment by EvilCalf** [comment] 2023-01-23 12:13
I'm sorry, I can't find the common point for this problem.

**Comment by trickerer** [comment] 2023-01-23 12:24
What happens if you log out at bots' spawn area? Try to observe from a different character (launch 2 clients, you'll need a different account).

Also, post a `/bonk` result on such a bot when game says it's inactive (you can do this to bot not owned by you in gm mode).

**Comment by trickerer** [comment] 2023-02-28 05:23
A month without answer. This issue will be marked at stall and closed in 3 days.

**Comment by AlvinZhu** [comment] 2023-03-02 10:09
I shared my modified AzerothCore  with NPCBots in a forum and some people and me are playing with it. We really like your NPCBots! 
I noticed that 3 player also gave feedback about similar problems.
The npcbots are spawned on GM island.
The player use .npcbot info to see that there were already 2 npcbot for his character, but they were not active and were unbiund, but he used .npcbot rebind to rebind them with no effect. He didn't see his hired bots back on gm island, so now he don't know where his npcbots have gone and where to find them again after he come back online.
Another player said his solution is to restart worldserver.
I will continue to follow up and ask the player for details, hopefully I can help.

**Comment by trickerer** [comment] 2023-03-02 12:26
Well, good.
Infinite path point search is supposed to be fixed now, but since this issue is still happening there must be something else.
I didn't see anything like this on my end. I need to know what state bot is in to even start to guess what could've caused that. Maybe bot has invalid coords, may bot is not alive, maybe they just out of world and not finishing their teleport or something. That's why I ask for an observation, as I don't expect anyone to debug the core and dig for suspicious values.

**Comment by AlvinZhu** [comment] 2023-03-02 14:04
I didn't see anything like this on my end also. If I see, Maybe I can find something.
More feedback from the player:
He hired two npcbots, a paladin and a priest. Then it was time to do quests and upgrades. He went offline at the Ratchet City Inn and was in a party with the npcbots when he went offline. When he logged in again he noticed that the bot was missing, then he used the npcbot command to check and found that he had 2 bots for this character, but they were both unbind, then he teleported to GM Island to look for them and didn't find them. His account did not have GM access, he set gmlevel 3 and then entered the game again. using the .npcbot move botID command to call the bot, then he was able to regroup by clicking on it.

another player, He had another problem, Maybe this is related to this issue:
He went offline at the City Inn. next time he start the server:
Starting NpcBot system...
/>> Bot spellInfo overrides generated for 44 spells
/>> Bot appearance data loaded
/>> Bot race data loaded
/>> Bots transmog data is not loaded. Table `characters_npcbot_transmog` is empty!
/>> Loaded 85 bot data entries
then the worldserver crash.
![213744tkw415e5ots3ho44](https://user-images.githubusercontent.com/4264000/222447712-5c9a17aa-e5b4-4944-a134-660f6c2ed0a2.jpg)

I guess these two players may have a common habit: logs out immediately after use Hearthstone return to the Inn.
I will be test this situation a few times myself to see what happens.

**Comment by trickerer** [comment] 2023-03-02 14:38
As for assertion, seems like debug info need to be attached in that assert statement so it will show what map bot tries to teleport to.

**Comment by trickerer** [comment] 2023-03-02 15:11
> He hired two npcbots, a paladin and a priest. Then it was time to do quests and upgrades. He went offline at the Ratchet City Inn and was in a party with the npcbots when he went offline. When he logged in again he noticed that the bot was missing, then he used the npcbot command to check and found that he had 2 bots for this character, but they were both unbind, then he teleported to GM Island to look for them and didn't find them. His account did not have GM access, he set gmlevel 3 and then entered the game again. using the .npcbot move botID command to call the bot, then he was able to regroup by clicking on it.

If `.npcbot move` command solved the issue (teleported the bot in question) then bot was alive and in world, which means bot most likely was somewhere too far from spawn point to reach it. This is strange since GM Island is too far from Ratchet for bot to make their way there on foot, they would teleport to home position directly.

**Comment by AlvinZhu** [comment] 2023-03-06 15:33
crash after I log in to my character:
the first time, I don't have the debugger on:
```
#----------------------------------------------------------------------#
 
>> ASSERTION FAILED

# Location '/backups/wow/azerothcore/src/server/game/Entities/Object/Object.h:523'
# Function 'GetMap'
# Condition 'm_currMap'

# Debug info: 'MapID: 1 X: 16237.5 Y: 16294.2 Z: 22.3877 O: 1.51619
GUID Full: 0xf130011257000043 Type: Creature Entry: 70231  Low: 67 Entry 70231
Name: 阿雷纳AliveState: true UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 5
AIName:  ScriptName: priest_bot WaypointPath: 0 SpawnId: 3110667'
 
#----------------------------------------------------------------------#
[1]    1444142 segmentation fault (core dumped)  ./worldserver
```

The second time(Did not reopen the client)：
```
#----------------------------------------------------------------------#
 
>> ASSERTION FAILED

# Location '/backups/wow/azerothcore/src/server/game/Entities/Object/Object.h:523'
# Function 'GetMap'
# Condition 'm_currMap'

# Debug info: 'MapID: 1 X: 16243.6 Y: 16296.3 Z: 20.945 O: 1.5854
GUID Full: 0xf13001134000006b Type: Creature Entry: 70464  Low: 107 Entry 70464
Name: 曼陀罗
AliveState: true UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 6
AIName:  ScriptName: death_knight_bot WaypointPath: 0 SpawnId: 3110707'
 
#----------------------------------------------------------------------#
Signal: SIGSEGV (Segmentation fault)

```
Stack:
```
Acore::Assert Errors.cpp:112
WorldObject::GetMap Object.h:523
Cell::VisitAllObjects<…> CellImpl.h:217
UnitAura::FillTargetMap SpellAuras.cpp:2890
Aura::UpdateTargetMap SpellAuras.cpp:611
Aura::ApplyForTargets SpellAuras.h:122
Unit::AddAura Unit.cpp:19923
bot_ai::RefreshAura bot_ai.cpp:3493
death_knight_bot::death_knight_botAI::ApplyClassPassives bot_death_knight_ai.cpp:1858
bot_ai::SetStats bot_ai.cpp:2227
bot_ai::DefaultInit bot_ai.cpp:13175
death_knight_bot::death_knight_botAI::Reset bot_death_knight_ai.cpp:1747
BotMgr::AddBot botmgr.cpp:1209
bot_ai::SetBotOwner bot_ai.cpp:395
bot_ai::FindMaster bot_ai.cpp:13851
bot_ai::GlobalUpdate bot_ai.cpp:16269
death_knight_bot::death_knight_botAI::UpdateAI bot_death_knight_ai.cpp:557
Creature::Update Creature.cpp:867
Acore::ObjectUpdater::Visit<…> GridNotifiers.cpp:355
VisitorHelper<…> TypeContainerVisitor.h:44
VisitorHelper<…> TypeContainerVisitor.h:50
VisitorHelper<…> TypeContainerVisitor.h:51
VisitorHelper<…> TypeContainerVisitor.h:57
TypeContainerVisitor::Visit TypeContainerVisitor.h:91
Grid::Visit<…> Grid.h:89
NGrid::VisitGrid<…> NGrid.h:103
Map::Visit<…> Map.h:877
Map::VisitNearbyCellsOf Map.cpp:735
Map::Update Map.cpp:812
MapUpdateRequest::call MapUpdater.cpp:44
MapUpdater::WorkerThread MapUpdater.cpp:156
std::__invoke_impl<…> invoke.h:74
std::__invoke<…> invoke.h:96
std::thread::_Invoker::_M_invoke<…> std_thread.h:258
std::thread::_Invoker::operator() std_thread.h:265
std::thread::_State_impl::_M_run std_thread.h:210
std::execute_native_thread_routine 0x00007ffff74d72c3
<unknown> 0x00007ffff729ebb5
<unknown> 0x00007ffff7320d90
```

Third time(Clear client cache and restart client):
No more crashes, I don't know if this is relevant?

my character logout at Shattrath City.
I made some other updates and the guid for NPCBots in the acore_world.creature table has changed. I don't know if this is relevant?

**Comment by AlvinZhu** [comment] 2023-03-07 06:37
2 more people have the same issue today: ASSERTION FAILED of GetMap

**Comment by trickerer** [comment] 2023-03-07 07:19
Try with these changes:
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/489ac398597239c3bd46465fc92e8870ffcea527
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c286d1ee3fed22a6f52e4da03ad0e07e5e71c898

They should prevent this crash, but try and see if console shows errors about free bots not in world

**Comment by AlvinZhu** [comment] 2023-03-07 08:20
> Try with these changes: [trickerer/AzerothCore-wotlk-with-NPCBots@489ac39](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/489ac398597239c3bd46465fc92e8870ffcea527) [trickerer/AzerothCore-wotlk-with-NPCBots@c286d1e](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c286d1ee3fed22a6f52e4da03ad0e07e5e71c898)
> 
> They should prevent this crash, but try and see if console shows errors about free bots not in world

Your projects are of high quality and you are patient and prompt with user feedback. Thank you very much, I will share these latest changes with my friends to test it.

**Comment by AlvinZhu** [comment] 2023-03-09 00:02
![2BD41937-A211-41D5-B7B9-02B9C21AF8A5](https://user-images.githubusercontent.com/4264000/223880545-281d859b-8283-449d-939c-ee4ecb632707.png)

crash Again with these changes


> Try with these changes: [trickerer/AzerothCore-wotlk-with-NPCBots@489ac39](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/489ac398597239c3bd46465fc92e8870ffcea527) [trickerer/AzerothCore-wotlk-with-NPCBots@c286d1e](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c286d1ee3fed22a6f52e4da03ad0e07e5e71c898)
> 
> They should prevent this crash, but try and see if console shows errors about free bots not in world

**Comment by trickerer** [comment] 2023-03-09 05:40
Well, suffice it to say that I have no idea what happens down the `FindMaster()` call such that causes bot to leave world, unless `MapUpdate.Threads` is set to something above 1 in config.
Without full Debug crashlog all I can do is try to find the place where this happens with additional checks.
For now I added the check right in `UnitAura::FillTargetMap()` (such check exists in TC but not in AC): https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/b938c1d427f5f121068108f1a5d4538acd825a45

**Comment by AlvinZhu** [comment] 2023-03-09 07:37
MapUpdate.Threads = -1 in the previous version I released on Feb 26, 2023.  
But I looked at the source code of AC and it seems that -1 is invalid. 
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/b938c1d427f5f121068108f1a5d4538acd825a45/src/server/game/Maps/MapMgr.cpp#L64
So. I set MapUpdate.Threads = 2 in the new version I released on Mar 8, 2023.
Both versions crash in this function:WorldObject::GetMap

I used to use JetBrains CLion debugging and I don't know how to export the full crashlog.
I will try to get the crashlog using this tutorial method: https://www.azerothcore.org/wiki/how-to-restart-and-debug
`gdb -x gdb.conf --batch ./worldserver`
Thank you.

**Comment by AlvinZhu** [comment] 2023-03-09 08:20
I'm so lucky. I caught the logs, and I found a way to 100% reproduce the problem.

leran this spell: Black Qiraji Battle Tank (can fly and Instant). Many people like to use it
.learn 31700

Teleport to Shattrath City, use this mount to fly in the air, and get offline.
When you come back online you will encounter this bug.

If you go online and dismount as soon as possible, or hide npcbots, you may avoid a server crash.

[gdb_crash.txt](https://github.com/trickerer/Trinity-Bots/files/10929302/gdb_crash.txt)

**Comment by trickerer** [comment] 2023-03-09 08:47
NPCs using AI cannot be teleported safely between maps with MapUpdate.Threads > 1.
Normally this results in assertion fail in Unit::RefreshAI()
Please use MapUpdate.Threads = 1 if you use NPCBots.

I need to add this to readme or something...

**Closed** 2023-03-11 07:34 UTC
Labels: bug
