### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by Spik3y** [trickerer/Trinity-Bots#665] opened 2023-10-19 07:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

After applying patch npcbot.patch I am able to have success with Cmake but when I try to compile using MS Visual Studio I get this error upon completion, further more if I compile my Trinity server without the bot patch there is no issue, here's the error in MS VS

21>H:\Trinity\trinitycore\src\server\game\Maps\Map.cpp(3777,18): error C2065: 'c': undeclared identifier
21>H:\Trinity\trinitycore\src\server\game\Maps\Map.cpp(3778,76): error C2065: 'c': undeclared identifier
20>spell_shaman.cpp
20>spell_warlock.cpp
21>H:\Trinity\trinitycore\src\server\game\Maps\Map.cpp(3778,95): error C2065: 'c': undeclared identifier
21>H:\Trinity\trinitycore\src\server\game\Maps\Map.cpp(3778,59): error C2661: 'Trinity::ComputeCellCoord': no overloaded function takes 1 arguments
21>H:\Trinity\trinitycore\src\server\game\Maps\Map.cpp(3778,59): message : while trying to match the argument list '()'
21>H:\Trinity\trinitycore\src\server\game\Maps\Map.cpp(3778,116): error C2065: 'c': undeclared identifier

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

Newest Trinitycore files as of 10/16/23

### Operating system

Windows 11

**Comment by trickerer** [comment] 2023-10-19 09:17
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/654

Please use a patched repository if that's an option for you

**Closed by trickerer** 2023-10-19 09:17 UTC
Labels: bug

**Comment by Spik3y** [comment] 2023-10-19 14:13
TBH not sure what you mean I'm new to this, I have patched a build last year and it worked fine so a patched repository would be great to try I have tried one I thought was patched with same results if you could point me in the direction of a patched version that would be helpful.

**Comment by trickerer** [comment] 2023-10-20 00:53
It's right there in my repositories list.
https://github.com/trickerer?tab=repositories
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots
