### ISSUE TITLE
Running the battlefield robot function may cause crashes[TC] [AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by songjunst** [trickerer/Trinity-Bots#590] opened 2023-08-03 10:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I am running the Battlefield function on the server, and the system program crashes while the player is using it. Sometimes it may not occur, but it may have triggered a certain bug.

### Expected behaviour

Turn off battlefield function testing and no longer experience crashes

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

worldserver

### Operating system

win10

**Comment by trickerer** [comment] 2023-08-12 11:16
Post a crashlog, without it there is no way I can help you.

**Comment by trickerer** [comment] 2023-08-23 00:39
Probably a duplicate of #611.
Could be closed by https://github.com/trickerer/Trinity-Bots/commit/71d0a5307db0f3de65fb8fdf56e71b9f5dbab088

**Closed by trickerer** 2023-08-23 00:39 UTC
Labels: bug
