### ISSUE TITLE
[TC] [AC] [Crash on Compile] [Core] The identifier "c" is not defined

### ISSUE THREAD

**Issue by MichaTausKamR** [trickerer/Trinity-Bots#666] opened 2023-10-22 00:25 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When compiling, I get the above error message and the worldserver.exe is not created.

### Expected behaviour

Compiling should run through.

### Crashlog

https://gist.github.com/MichaTausKamR/4f8e10446799715c0a9595af62bc50a2

### Steps to reproduce the problem

1) Clean install of TrinityCore
2) Apply patch
3) Start compiling

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. d5b64a0bb23c+ 2023-10-18 20:21:53 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win Server 2012 R2

**Comment by trickerer** [comment] 2023-10-22 00:43
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/654
See also: https://github.com/trickerer/Trinity-Bots/issues/665

Thanks for ruining issue 666

**Closed by trickerer** 2023-10-22 00:43 UTC
Labels: bug
