### ISSUE TITLE
Notes from players

### ISSUE THREAD

**Issue by Slipy007** [trickerer/Trinity-Bots#184] opened 2022-06-24 08:25 UTC
Player notes I got:

1. I had to dismiss a bot to fix it because it stopped moving and when I tried to rehire him, he killed me lol.

2. Yeah I had one that got stuck in a doorway in Dal and wouldn't respond. I lost all the gear I had on him.

**Comment by trickerer** [comment] 2022-06-24 09:28
1. I have never seen a bot stop moving on their own, except due to unit states bug where creature retains some of the unit states caused by different spell effects such as UNIT_STATE_STUNNED. It is typically fixed by `/tickle`. Mentioned in the README:
> `kill`|`suicide` -- (Player command) forces a NPCBot to die. Designed for troubleshooting in situations like when NPCBots are not acting normally. This can be caused by a rare bug causing creatures to retain Unit States. If this doesn't work, try to `/tickle` them 

As for the rehiring incident:
> `You are dismissed` will remove the NPCBot from your control. They will become pissed off, throw all their gear at you and return back to their spawn location. They will also become enraged for 5 minutes to the point where they will attack anyone attempting to hire them

2. Which one? [What does that even mean?](https://m.youtube.com/watch?v=J4K7Y-IpTl0&t=53s) Why didn't they just try to relog?

**Comment by Slipy007** [comment] 2022-06-24 10:54
> 1. I have never seen a bot stop moving on their own, except due to unit states bug where creature retains some of the unit states caused by different spell effects such as UNIT_STATE_STUNNED. It is typically fixed by `/tickle`. Mentioned in the README:
> 
> > `kill`|`suicide` -- (Player command) forces a NPCBot to die. Designed for troubleshooting in situations like when NPCBots are not acting normally. This can be caused by a rare bug causing creatures to retain Unit States. If this doesn't work, try to `/tickle` them
> 
> As for the rehiring incident:
> 
> > `You are dismissed` will remove the NPCBot from your control. They will become pissed off, throw all their gear at you and return back to their spawn location. They will also become enraged for 5 minutes to the point where they will attack anyone attempting to hire them
> 
> 2. Which one? [What does that even mean?](https://m.youtube.com/watch?v=J4K7Y-IpTl0&t=53s) Why didn't they just try to relog?

Ok thank you @trickerer I should of read the readme first.

**Closed** 2022-06-24 11:18 UTC
