### ISSUE TITLE
[AC] [Bug] [Spell] SpellScript Errors

### ISSUE THREAD

**Issue by AsurasWrathX** [trickerer/Trinity-Bots#913] opened 2024-11-02 14:56 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

After updating today i get the following SpellScript Errors:

Validating Spell Scripts...
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `65950` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `66001` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `67281` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `67282` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `67283` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `67296` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `67297` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
_SpellScript::ValidateSpellInfo: Spell 176 does not exist.
_SpellScript::_Validate: Spell `67298` did not pass Validate() function of script `spell_valkyr_touch_aura` - script will not be added to the spell
>> Validated 2584 scripts in 10 ms

Is there any way to fix that?

Thanks in advance

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 7754879ae10c 2024-11-02 05:25:08 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win11

**Comment by trickerer** [comment] 2024-11-03 06:29
Caused by https://github.com/azerothcore/azerothcore-wotlk/commit/bbbcaac77c86d648690f71b6a7d9c2915b4804fb, nothing bot-related

Wait until the official fix by AC devs is merged

**Closed by trickerer** 2024-11-03 06:29 UTC
Labels: bug
