### ISSUE TITLE
[TC] Core

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#608] opened 2023-08-20 20:02 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The patch from 8/15/23 is no longer compatible with the last TC update.

Will there be another fix?

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

[1bea4aa](https://github.com/TrinityCore/TrinityCore/commit/aaa6e73c8ca6d60e943cb964605536eb78219db2)

### Operating system

Debian 11

**Comment by trickerer** [comment] 2023-08-21 00:20
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/603

Yes, it will be fixed, have patience

**Closed by trickerer** 2023-08-21 00:20 UTC
Labels: bug
