### ISSUE TITLE
[AC] [NPCBots] Npcbots disappeared from where they were spawned.

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#449] opened 2023-05-06 07:10 UTC
Hi, I used the latest repo and found that Npcbots disappeared from where they were spawned, but when I checked the .npcbot list spawned, they were listed there. I wonder how?
Npbots also disappeared from my group, They also don't appear on recall and unhide.

Here are some screenshots: 

![untitled](https://user-images.githubusercontent.com/68382531/236608898-84dfdaca-dfcf-4860-a3c8-1e49c2676502.JPG)

![WoWScrnShot_050623_140033](https://user-images.githubusercontent.com/68382531/236609037-f9c83f9a-80bb-4406-8811-abe1d4478510.jpg)

**Comment by trickerer** [comment] 2023-05-06 07:20
You probably just can't see them. You can see the pet which is always next to its summoner.
It may happen sometimes that their models don't show for some reason. Try teleporting somewhere and then going back. Try restarting the server.

**Comment by zaicopx** [comment] 2023-05-06 07:25
I've tried restarting the server and it's the same.  Ok, I'll try to log in later using the client without the HD texture mod.

**Comment by trickerer** [comment] 2023-05-06 07:28
Try using `.npcbot go` to each of them to check their exact location

**Comment by zaicopx** [comment] 2023-05-06 07:42
I just tried to hire bot using Npc hire bot and it crashes.  Now I'm building in debug mode.  I'll try to upload the debug error later.

**Comment by zaicopx** [comment] 2023-05-06 08:39
Here the crashlog
[Crashes.zip](https://github.com/trickerer/Trinity-Bots/files/11411901/Crashes.zip)

**Comment by trickerer** [comment] 2023-05-06 08:43
Looks like a duplicate of #446 - missing SQL updates

**Comment by zaicopx** [comment] 2023-05-06 08:59
Ahhh, I seem to have forgotten this:
2023_04_28_00_creature_template.sql

OK, I'll try again.

**Comment by zaicopx** [comment] 2023-05-06 09:24
I think I can see them again. Thank you

![WoWScrnShot_050623_162152](https://user-images.githubusercontent.com/68382531/236615581-10c6cf69-a0ad-4e99-a16b-98c2ee3f468d.jpg)

**Closed** 2023-05-06 09:24 UTC
