### ISSUE TITLE
[AC] [Bug] [Spell] Unknown Spell error in Worldserver cli

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#886] opened 2024-09-28 15:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![SpellError_AzerothCoreNPCBots_worldserver exe](https://github.com/user-attachments/assets/426a2128-215d-4398-a0ab-ceb41ae44102)

I get sporadic errors when the server is running - if I remove the wanderbots, the errors stops.

Server compiled today using:
AzerothCore-wotlk-with-NPCBots
mod-autobalance (trickerer branch)
mod-ah-bot
mod-challenge-modes
mod-individual-progression
mod-pvp-titles
mod-reagent-bank
mod-transmog

### Steps to reproduce the problem

Start server with Wanderbots enabled, wait for them to naturally produce the errors.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 7fabb6d92472 2024-09-28 07:12:17 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win11

**Comment by trickerer** [comment] 2024-09-29 00:13
Looks like a duplicate of #245, #253

**Comment by Badgermilk0** [comment] 2024-09-29 08:34
I'm not running EnchantMods - but you are likely correct.
I believe IndividualProgression modifies some rogue abilities - but I can't find the reference 7614 anywhere. =(

I'm assuming this is not really a NPCbot issue then but rather a compatibility issue with another mod.

**Comment by Badgermilk0** [comment] 2024-09-30 06:21
Likely not a NPCbot issue but a compatibility issue from another mod.

**Closed** 2024-09-30 06:21 UTC
Labels: bug
