### ISSUE TITLE
 [AC] [Spell] Damage Per Second needs to be optimized

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#319] opened 2023-01-11 04:10 UTC
In the current version, theDamage Per Second of melee physics class is much better than that of ranged spell class,For example, the Damage Per Second of WARRIOR, HUNTER, and death-knight is much better than that of mages, priests, warlocks, and druids.At the same equipment level.

**Comment by trickerer** [comment] 2023-01-11 05:04
Duplicate of #301

**Closed by trickerer** 2023-01-11 05:04 UTC
Labels: bug, duplicate, enhancement
