### ISSUE TITLE
[AC] [Bug] [Group] Shaman Bots in party cause player to get stuck in combat

### ISSUE THREAD

**Issue by BelRepor** [trickerer/Trinity-Bots#788] opened 2024-05-02 22:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Whenever i run dungeons or raids with shaman bots they cause the group to get stuck in combat. maybe totem related.

### Expected behaviour

Combat should clear after defeating all engaged mobs with a shaman bot in the party.

### Steps to reproduce the problem

1) have a shaman bot in group
2)engage in combat
3)get stuck in combat after defeating the mobs

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 9ca9f695998c+ 2024-03-25 07:46:25 -0600 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win11

**Comment by trickerer** [comment] 2024-05-14 08:33
Sorry but this isn't very helpful. Bots themselves rarely cause this kind of problems, it's mostly some other creature that keeps the aggro on one of your party.
Without context it's absolutely impossible to figure out what is the problem exactly. This would at least require output of `.debug hostile` and `.debug threat` on you and the bot in question.

**Comment by Boxhead78** [comment] 2024-06-01 15:20
I noticed this happening frequently with shaman bots in party and noticed that it might be due to bot totems. Every time I had this issue I let my shaman bot disband its totems and I wasn't stuck in combat any longer.

However I didn't play with a shaman bot in my group for some time now. I will observe it a bit more when I encounter this bug again and try to give more info.

**Comment by trickerer** [comment] 2024-06-01 15:28
Post your Shaman's roles, spec and disabled spells if any.

**Comment by trickerer** [comment] 2024-08-12 06:54
No answer in two months. In fact, if the issue is totems-related then  it's purely AC threat manager issue as bot totems are no different from player's.
Closing now.

**Closed by trickerer** 2024-08-12 06:54 UTC
Labels: bug
