### ISSUE TITLE
[AC] [Bug] Newly created NPCBots are visibly showing up incorrectly

### ISSUE THREAD

**Issue by fatherzen** [trickerer/Trinity-Bots#733] opened 2024-01-30 00:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Created a new NPCBot .npcbot createnew Nynette 1 1 1 9 5 1 5 2

![image](https://github.com/trickerer/Trinity-Bots/assets/158113285/84cac45d-e354-4a34-9161-0cd2c2077eca)

Restart Server

.npcbot spawn 70811

![image](https://github.com/trickerer/Trinity-Bots/assets/158113285/aa2575be-9612-44e7-9670-4b3f25bcabee)
![image](https://github.com/trickerer/Trinity-Bots/assets/158113285/df4634e8-f48a-4274-a13b-5c03e63d92df)

Talking to the NPCBot and choosing nevermind shows the dialog in chat using the right name. 

DB shows correct as far as I can tell.

creature_template shows entry as follows -

{
"creature_template": [
	{
		"entry" : 70811,
		"difficulty_entry_1" : 0,
		"difficulty_entry_2" : 0,
		"difficulty_entry_3" : 0,
		"KillCredit1" : 0,
		"KillCredit2" : 0,
		"modelid1" : 1295,
		"modelid2" : 0,
		"modelid3" : 0,
		"modelid4" : 0,
		"name" : "Nynette",
		"subname" : "Warrior Bot",
		"IconName" : "",
		"gossip_menu_id" : 0,
		"minlevel" : 80,
		"maxlevel" : 80,
		"exp" : 2,
		"faction" : 35,
		"npcflag" : 1,
		"speed_walk" : 1.0,
		"speed_run" : 1.0,
		"speed_swim" : 1.0,
		"speed_flight" : 1.0,
		"detection_range" : 20.0,
		"scale" : 1.0,
		"rank" : 0,
		"dmgschool" : 0,
		"DamageModifier" : 1.0,
		"BaseAttackTime" : 3400,
		"RangeAttackTime" : 2000,
		"BaseVariance" : 1.0,
		"RangeVariance" : 1.0,
		"unit_class" : 1,
		"unit_flags" : 0,
		"unit_flags2" : 32,
		"dynamicflags" : 0,
		"family" : 0,
		"trainer_type" : 0,
		"trainer_spell" : 0,
		"trainer_class" : 0,
		"trainer_race" : 0,
		"type" : 7,
		"type_flags" : 4096,
		"lootid" : 0,
		"pickpocketloot" : 0,
		"skinloot" : 0,
		"PetSpellDataId" : 0,
		"VehicleId" : 0,
		"mingold" : 0,
		"maxgold" : 0,
		"AIName" : "",
		"MovementType" : 0,
		"HoverHeight" : 1.0,
		"HealthModifier" : 1.0,
		"ManaModifier" : 1.0,
		"ArmorModifier" : 1.0,
		"ExperienceModifier" : 1.0,
		"RacialLeader" : 0,
		"movementId" : 0,
		"RegenHealth" : 0,
		"mechanic_immune_mask" : 0,
		"spell_school_immune_mask" : 0,
		"flags_extra" : 2383413360,
		"ScriptName" : "warrior_bot",
		"VerifiedBuild" : -1
	}
]}

### Expected behaviour

NPCBots should spawn showing the right information?

### Steps to reproduce the problem

Create a new NPCBot using .npcbot createnew command
Restart server.
Spawn NPCBot. 
Results.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

da30653363

**Comment by trickerer** [comment] 2024-01-30 00:59
Delete your client's cache.

WoW client caches npc names and if you spawn a brand new npc with creature_id previously encountered in game you get this effect. With npcbots this is mainly caused by wandering bots

**Comment by fatherzen** [comment] 2024-01-30 01:11
Wild. I don't have wandering bots enabled. Maybe something in the cache was just busted on the client.  Thank you for being a fountain of knowledge. Search engines resulted nothing.

**Comment by trickerer** [comment] 2024-01-30 02:27
Closing

**Closed** 2024-02-22 12:45 UTC
Labels: bug
