### ISSUE TITLE
[TC] [AC] [Bug] [Spell] The problem of some skills not being able to be cast on NPCBOTS

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#806] opened 2024-05-21 07:31 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Player feedback:
1. In the game, the player's character is a hunter with a misleading skill (id=34477) that can cast spells on pets, but cannot be sent to NPC bots.
2. In the game, the player's character Paladin has a skill (id=53563) Holy Light Beacon, but cannot cast spells on NPC bots.

### Expected behaviour

Hope to fix the use of these two skills on npcbots
Thank you!

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 2031358 2024-05-18 13:46:18 +0800 (npcbots_3.3.5 branch) 

### Operating system

ubuntu 18.04

**Comment by trickerer** [comment] 2024-05-21 07:54
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/586. Learn to use `.npcbot useonbot` command

**Closed by trickerer** 2024-05-21 07:54 UTC
Labels: bug
