### ISSUE TITLE
Battlegrounds - Stats

### ISSUE THREAD

**Issue by Conan1996-2** [trickerer/Trinity-Bots#486] opened 2023-06-08 03:31 UTC
Love the battlegrounds! Huge step forward. I have been playing them a lot.

Some things of note:

- I have not been receiving buffs from bots before the start of the BG
- Stats window does not work at all, only shows your stats. I would love to see all stats of chars in the BG (# of chars, healing, dps, etc) This helps finding who the healers are, char types in BG, etc
- None of the characters show up on the map, so I have no idea where the team members are.
- I found that if I'm out of range of the NPC, the ones in my party appeared to be dead until in range.
- When the flag has been dropped by you or bot in WG, no one attempts to pick it up or return it, I've seen it time out while on the ground many times.
- In AB, no one stays at a captured base to "Defend", all bots just run around. if that was implemented, it would be nice if the BOT spoke in the BG chat that the "area" was under attack when it was attacked.

**Comment by trickerer** [comment] 2023-06-08 07:21
1) Yeah, noticed that, they buff each other but not player until they're free to move, weird.
2) Impossible. The only BG bot stat you can see is objectives completed (flags) because it has a separate handling. All other info is sent to player via a single packet type. The problem is that client expects player guid there, which bots don't have - and although all stats get properly collected server-side, client just discards it, even bot's team.
3) Same problem as (2), but here it seems like client doesn't request this info at all. Maybe some map addon can help.
4) Again, this is a client-side problem. It happens even with controlled bots for which, mind you, update packets are always sent to player, client just ignores it for non-players outside of visibility range. I saw an AC PR which was supposed to allow visibility range in BGs up to grid size, current maximum is 250 yards.
5) Bots ignore dropped flags rn, skipped that during initial BG bots development since there was no certainty as to where these checks go exactly.
6) BG bots have no 'defend point' concept. They do defend flag carrier and prioritize attacking enemy flag carrier. But in AB they don't have any special tactics. Not sure how I feel about that, but in general bots aren't supposed to outplay players in BG, like in WSG they are very unlikely to score even once without player tilting the scale.

**Comment by Conan1996-2** [comment] 2023-06-08 22:32
Understood, but cant the bots be assigned and entered into the character database, with an account that doesn't exist, like -1? This way, they would have an guid.

**Comment by trickerer** [comment] 2023-06-08 23:41
That's not the way it works.
First of all, GUID is Global Unique Identifier, unique for each object. You can't assign it to some constant and call it good.
Secondly, client expect **real** player guid. When client received it, first thing it checks is nearby players where client can get name and class info, but if not found - sends a player info request to the server and gets name and class this way.
That's why it's impossible to do. Unless there is some miraclous way in which there is a consistent player info request to intercept. Then *maybe* some info could be forged for the client.

**Comment by trickerer** [comment] 2023-06-10 14:39
https://github.com/trickerer/Trinity-Bots/commit/99dc54fd7d331a3c899cb42e9c0371946582914d and https://github.com/trickerer/Trinity-Bots/commit/1457dc8ebeb9c5f69554b775e2bb0059d767c6c3 fix 1, 2, 3 and 4.
As for the rest - they may get implemented in time but no promises.
Closing now.

**Closed by trickerer** 2023-06-10 14:39 UTC

**Comment by Conan1996-2** [comment] 2023-06-10 17:38
Huge and perfect update. thank you.
