### ISSUE TITLE
[AC] [Bug] [Spell] Keristrasza Intense Cold does not drop on movement.

### ISSUE THREAD

**Issue by KTM-JAY** [trickerer/Trinity-Bots#561] opened 2023-07-04 07:07 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The Keristraza Intense Cold debuff does not reset when the bots move, maxes out at nine stacks and promptly kills the bots.

### Expected behaviour

The debuff is supposed to drop off when you move, then start to apply when you stand still.  Move again and it drops.

### Steps to reproduce the problem

Just start the fight with bots.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 96a5224d927f+ 2023-04-22 07:25:31 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static)

### Operating system

Win 10

**Comment by trickerer** [comment] 2023-07-04 07:26
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/482

Search in existing issues before posting next time please.

**Closed by trickerer** 2023-07-04 07:26 UTC
Labels: bug
