### ISSUE TITLE
 [AC] [Bug]  After entering the dungeon, the robot's mana disappears.

### ISSUE THREAD

**Issue by mooonshae1979** [trickerer/Trinity-Bots#814] opened 2024-05-28 03:22 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![Befour entering the dungeon](https://github.com/trickerer/Trinity-Bots/assets/63702166/e7cf8e96-336f-48b2-bb62-b80b67778614)
After entering the dungeon, the robot's mana disappears.
The four robots from top to bottom are: sea witch, crypt lord, druid, and priest.
![After entering the dungeon](https://github.com/trickerer/Trinity-Bots/assets/63702166/d53f28be-ff29-4ee9-81ea-1bdbe381bf6f)
Bots cannot use any mana-based spells.
Only restart server can be recovery.

### Expected behaviour

Robot mana shouldn't disappear

### Steps to reproduce the problem

Entering the dungeon

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 4ecbc6fe8977 2024-05-25 22:37:03 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (authserver)

### Operating system

Ubuntu 20.04

**Comment by mooonshae1979** [comment] 2024-05-28 03:29
Compile with these mods: mod-ah-bot, mod-autobalance, mod-eluna, mod-learn-spells, mod-random-enchants

**Comment by mooonshae1979** [comment] 2024-05-28 04:05
I checked some historical issues and it seems that the conflict is caused by mod-autobalance.
I'll try to recompile with the npcbots branch, wish me luck.

**Comment by trickerer** [comment] 2024-05-28 07:35
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/735, https://github.com/trickerer/Trinity-Bots/issues/804

**Comment by mooonshae1979** [comment] 2024-05-28 10:09
Recompile with the mod-autobalance npcbots branch,It's fixed

**Closed** 2024-05-28 10:15 UTC
Labels: bug
